apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-creds
  namespace: db-app
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: kubernetes-backend
    kind: SecretStore
  target:
    name: postgres-creds
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: postgres-creds
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: postgres-creds
        property: password
    - secretKey: POSTGRES_DB
      remoteRef:
        key: postgres-creds
        property: database

