apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: kubernetes-backend
  namespace: db-app
spec:
  provider:
    kubernetes:
      remoteNamespace: eso-backend
      server:
        url: https://kubernetes.default.svc
      auth:
        serviceAccount:
          name: default

